version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    image: demystifying-wall-street-website
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
